Project/Marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('products/', include('products.urls', namespace='products')),
    path('profile/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('pages.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

Project/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('success/', views.order_success, name='order_success'),
    path('my-orders/', views.my_orders, name='my_orders'),
]

Project/products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns = [
    path('add/', views.add_product, name='add_product'),
    path('', views.product_list, name='product_list'),
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('categories/', views.category_list, name='category_list'),
    path('category/<slug:slug>/', views.products_by_category, name='products_by_category'),
    path('compare/', views.product_comparison_view, name='product_compare'),
    path('compare/add/<int:product_id>/', views.add_to_comparison_view, name='add_to_comparison'),
    path('compare/remove/<int:product_id>/', views.remove_from_comparison_view, name='remove_from_comparison'),
]

Project/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import profile_view, register, LogoutGetView

app_name = 'users'

urlpatterns = [
    path('', profile_view, name='profile'),
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutGetView.as_view(), name='logout'),
]

Project/templates/partials/footer.html
{% load i18n %}
<footer class="bg-light text-center py-3 mt-5">
    <p class="mb-0">&copy; 2025 BeatMotion. {% trans "All rights reserved." %}</p>
  </footer>
  

Project/templates/partials/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">{% trans "BeatMotion" %}</a>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">{% trans "Home" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:product_list' %}">{% trans "Products" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">{% trans "Services" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:cart_detail' %}">{% trans "Cart" %}</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'orders:my_orders' %}">{% trans "My Orders" %}</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:product_compare' %}">{% trans "Compare" %}</a>
          </li>
        </ul>

        <!-- Auth -->
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'users:profile' %}">{% trans "Profile" %}</a>
          <a class="nav-link" href="{% url 'logout' %}">{% trans "Logout" %}</a>
        {% else %}
          <a href="{% url 'users:login' %}" class="nav-link">Login</a>
          <a href="{% url 'users:register' %}" class="nav-link">Register</a>
          <p>
          <a class="nav-link" href="{% url 'social:begin' 'google-oauth2' %}">{% trans "Login with Google" %}</a>
          <noscript>
            <a class="nav-link" href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">{% trans "Login with Facebook" %}</a>
            <a class="nav-link" href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">{% trans "Login with X (Twitter)" %}</a>
          </noscript>
        {% endif %}

        <!-- Language Switcher -->
        <form action="{% url 'set_language' %}" method="post" class="d-flex ms-3">
          {% csrf_token %}
          <input name="next" type="hidden" value="{{ request.path }}">
          <select name="language" class="form-select form-select-sm me-2" onchange="this.form.submit()">
            <option value="en" {% if LANGUAGE_CODE == 'en' %}selected{% endif %}>EN</option>
            <option value="uk" {% if LANGUAGE_CODE == 'uk' %}selected{% endif %}>UA</option>
          </select>
        </form>
      </div>
    </div>
  </nav>
  